name: Updater
on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  Updater:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Update npm dependencies
        run: npx --yes npm-check-updates -u
      - name: Create pull request
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          checkout -b update-dependencies-${{ steps.date.outputs.date }}
          git add -A
          git commit -m "[UPDATE] Npm dependencies" && git push --set-upstream update-dependencies-${{ steps.date.outputs.date }} || echo "nothing to update"
        
